version: '3.8'

services:
  # SQL Server Database
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: bookstore-sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Password123
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - bookstore-network
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P YourStrong@Password123 -Q "SELECT 1" -C || exit 1
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s

  # BookStore API
  bookstore-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bookstore-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__UsersDb=Server=sqlserver;Database=ChuyenDeTongHop;User Id=sa;Password=YourStrong@Password123;MultipleActiveResultSets=true;TrustServerCertificate=True
    ports:
      - "5276:8080"
    depends_on:
      sqlserver:
        condition: service_healthy
    networks:
      - bookstore-network
    restart: on-failure

volumes:
  sqlserver_data:
    driver: local

networks:
  bookstore-network:
    driver: bridge
