pipeline {
    agent any

    environment {
        REGISTRY_URL = "localhost:5000"
        IMAGE_NAME   = "bookstore-backend"
        IMAGE_TAG    = "v1"
    }

    stages {

        stage('Checkout') {
            steps { checkout scm }
        }

        stage('Docker Build') {
            steps {
                sh '''
                    cd BE
                    docker build -t ${IMAGE_NAME}:${IMAGE_TAG} .
                '''
            }
        }

        stage('Push to Registry') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'docker-registry',
                    usernameVariable: 'REG_USER',
                    passwordVariable: 'REG_PASS'
                )]) {

                    sh '''
                        docker tag ${IMAGE_NAME}:${IMAGE_TAG} ${REGISTRY_URL}/${IMAGE_NAME}:${IMAGE_TAG}

                        echo "${REG_PASS}" | docker login ${REGISTRY_URL} -u "${REG_USER}" --password-stdin

                        docker push ${REGISTRY_URL}/${IMAGE_NAME}:${IMAGE_TAG}
                    '''
                }
            }
        }

        stage('Deploy') {
            steps {
                sh '''

                    # Chạy docker-compose cho SQL + MinIO
                    docker compose -f BE/docker/docker-compose.yml up -d

                    # Dừng container backend cũ
                    docker stop bookstore-backend || true
                    docker rm   bookstore-backend || true

                    # Pull backend version mới
                    docker pull ${REGISTRY_URL}/${IMAGE_NAME}:${IMAGE_TAG}

                    # Chạy backend
                    docker run -d \
                        --name bookstore-backend \
                        --network docker_bookstore-network \
                        -e ASPNETCORE_ENVIRONMENT=Development \
                        -e ConnectionStrings__UsersDb="Server=bookstore-sqlserver,1433;Database=BookStore;User Id=bookstoreUser;Password=BookstorePass1@;MultipleActiveResultSets=true;TrustServerCertificate=True" \
                        -e MinIO__Endpoint=bookstore-minio:9000 \
                        -e MinIO__AccessKey=minioadmin \
                        -e MinIO__SecretKey=minioadmin123 \
                        -e MinIO__BucketName=bookstore-images \
                        -e MinIO__UseSSL=false \
                        -p 3030:8080 \
                        ${REGISTRY_URL}/${IMAGE_NAME}:${IMAGE_TAG}
                '''
            }
        }
    }
}
